version: "3.9"
services:
  db:
    container_name: infraction-central-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: k29DlaweP65
      POSTGRES_DB: infraction-central
    ports:
      - "5432:5432"
    # volumes:
    #   - db-data:/var/lib/postgresql/data

  backend:
    container_name: infraction-central-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/infraction-central
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: k29DlaweP65
    ports:
      - "8080:8080"

  frontend:
    container_name: infraction-central-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5173:5173"

# volumes:
#   db-data:
